### ISSUE TITLE
Find the `commons_download_tool.py` file and command on Wikimedia servers

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/CommonsDownloadTool#2]
Page **https://lingualibre.org/datasets/** is an important page to share LL's recording to the outside world : open sources and for profits projects outside the Wikimedia galaxy.

The standalone python file `commons_download_tool.py` seems to be the script generating the `datasets` page cited above. 

This daily script have not run since April 2020. 

In order to fix it, the follwing steps are required : 
- [x] @mickeybarber: On wikimedia servers, find where  the files `operations/create_datasets.sh` and `CommonsDownloadTool/commons_download_tool.py` are hosted. Confirm you have read/write access on this.
- [x] Find where is the command `python3 commons_download_tool.py` is called.
- [x] Find the exact command calling `commons_download_tool.py` (with parameters) and share it back here. Following inspection of the code, it is suspect that the parameter `--sparql` will be defined in the command with a meaningful value.

Given these informations, a competent wikimedian with python & sparql knowledge will test and tinker  `commons_download_tool.py`'s command in order to propose a diagnosis and possibly a working solution.

**Comment by hugolpz** [comment]
I eventually found (2) the call and (3) the command.

They are in repository and file [`operations/create_datasets.sh`](https://github.com/lingua-libre/operations/blob/master/create_datasets.sh). Command to try locally is : 
```shell
python3 ./commons_download_tool.py --keep --sparqlurl https://lingualibre.fr/bigdata/namespace/wdq/sparql --sparql "SELECT ?file ?filename WHERE { ${query} ?record prop:P4 entity:${qid}. }" --threads 4 --directory  /tmp/datasets/raw/ --output "./${qidpath##*/}.zip" --fileformat ogg
```

I have near zero python skills, and didn't installed any library. The error I get is : 
```python
python3 ./commons_download_tool.py --keep --sparqlurl https://lingualibre.fr/bigdata/namespace/wdq/sparql --sparql "SELECT ?file ?filename WHERE { ${query} ?record prop:P4 entity:${qid}. }" --threads 4 --directory  /tmp/datasets/raw/ --output "./${qidpath##*/}.zip" --fileformat ogg
Traceback (most recent call last):
  File "./commons_download_tool.py", line 220, in <module>
    get_params()
  File "./commons_download_tool.py", line 208, in get_params
    response = json.loads(response.text)['results']['bindings']
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by hugolpz** [comment]
@mickeybarber : I think the issue is just the need to migrate from `lingualibre.fr` to `lingualibre.org`.

**Comment by hugolpz** [comment]
### 2021/01/27:
```
../
Q101-srr-Serer.zip                                 05-Nov-2019 03:09               14967
Q113-cmn-Mandarin Chinese.zip                      05-Nov-2019 03:09              112613
Q115107-bcl-Central Bikol.zip                      05-Nov-2019 03:09              166323
Q123-hin-Hindi.zip                                 25-Apr-2020 03:30             1704401
Q126-por-Portuguese.zip                            25-Apr-2020 03:31            43732966
Q127-tam-Tamil.zip                                 05-Nov-2019 03:09              154352
Q129-rus-Russian.zip                               25-Apr-2020 03:32            60844464
Q130-zho-Chinese.zip                               05-Nov-2019 03:10             2724328
Q131-hye-Armenian.zip                              05-Nov-2019 03:10              824117
Q141-cym-Welsh.zip                                 05-Nov-2019 03:10            12905993
Q150-afr-Afrikaans.zip                             25-Apr-2020 04:18            42363003
Q154-amh-Amharic.zip                               05-Nov-2019 03:11             2653977
Q159-dyu-Dioula language.zip                       25-Apr-2020 04:18              784432
Q165-hat-Haitian Creole.zip                        05-Nov-2019 03:11              233588
Q169-tgl-Tagalog.zip                               05-Nov-2019 03:11               77198
Q170137-mos-Mossi.zip                              05-Nov-2019 03:11             1158142
Q19858-bci-BaoulÃ©.zip                             25-Apr-2020 04:18             1268304
Q203-cat-Catalan.zip                               25-Apr-2020 04:18             9738365
Q204940-ken-Nyang language.zip                     25-Apr-2020 04:18              483396
Q205-gre-Greek.zip                                 05-Nov-2019 03:11              239390
Q208-vie-Vietnamese.zip                            25-Apr-2020 04:18             8822067
Q21-fra-French.zip                                 25-Apr-2020 05:10          2112950650
Q219-ara-Arabic.zip                                25-Apr-2020 04:19            85373129
Q22-eng-English.zip                                25-Apr-2020 05:12           131688602
Q221062-mis-Cantonese.zip                          25-Apr-2020 05:10             3895600
Q231-myv-Erzya.zip                                 05-Nov-2019 03:21              205878
Q24-deu-German.zip                                 25-Apr-2020 05:15           234412068
Q242-fon-Fon.zip                                   05-Nov-2019 03:21             1538614
Q25-epo-Esperanto.zip                              25-Apr-2020 05:19           445662713
Q258-nso-Northern Sotho.zip                        05-Nov-2019 03:24              774299
Q264201-ary-Moroccan Arabic.zip                    25-Apr-2020 05:19             1371064
Q273-kab-Kabyle.zip                                25-Apr-2020 05:19              370876
Q298-pol-Polish.zip                                25-Apr-2020 05:21           145009958
Q299-eus-Basque.zip                                25-Apr-2020 05:21            46035866
Q307-ben-Bengali.zip                               25-Apr-2020 05:46            16504691
Q311-oci-Occitan.zip                               05-Nov-2019 03:33           511332485
Q318-bam-Bambara.zip                               05-Nov-2019 03:33              277786
Q321-gaa-Ga.zip                                    05-Nov-2019 03:33             3247380
Q33-fin-Finnish.zip                                25-Apr-2020 05:46            19473062
Q336-ori-Odia.zip                                  05-Nov-2019 03:34            38697693
Q339-sat-Santali.zip                               05-Nov-2019 03:34              128941
Q34-mar-Marathi.zip                                05-Nov-2019 03:34             2274397
Q35-nld-Dutch.zip                                  05-Nov-2019 03:34            36279372
Q385-ita-Italian.zip                               05-Nov-2019 03:34             3440247
Q386-spa-Spanish.zip                               25-Apr-2020 05:46            28434220
Q388-que-Quechua.zip                               05-Nov-2019 03:35              397476
Q389-jpn-Japanese.zip                              25-Apr-2020 05:46              145688
Q39-tel-Telugu.zip                                 05-Nov-2019 03:35               85571
Q392-ces-Czech.zip                                 25-Apr-2020 05:46               96844
Q397-heb-Hebrew.zip                                05-Nov-2019 03:35             1657223
Q405-bas-Basaa language.zip                        05-Nov-2019 03:35             1515700
Q437-mal-Malayalam.zip                             05-Nov-2019 03:35              138601
Q44-swe-Swedish.zip                                25-Apr-2020 05:46              166237
Q446-pan-Punjabi.zip                               05-Nov-2019 03:35               11004
Q4465-mis-Teochew dialect.zip                      05-Nov-2019 03:35               69734
Q45-nor-Norwegian.zip                              05-Nov-2019 03:35              431566
Q46-ltz-Luxembourgish.zip                          05-Nov-2019 03:35             1679618
Q4901-shy-Shawiya language.zip                     25-Apr-2020 05:47            15804835
Q51299-hav-Havu.zip                                05-Nov-2019 03:37               56823
Q51302-tay-Atayal.zip                              05-Nov-2019 03:37               65533
Q52067-bbj-Ghomala' language.zip                   05-Nov-2019 03:37             1765823
Q52068-bum-Bulu language.zip                       05-Nov-2019 03:37             1382789
Q52071-dua-Duala.zip                               05-Nov-2019 03:37             1206427
Q52073-bdu-Oroko.zip                               05-Nov-2019 03:37             1723960
Q52074-bzm-Londo.zip                               05-Nov-2019 03:37             1750380
Q52295-atj-Atikamekw.zip                           05-Nov-2019 03:37             7315215
Q6714-arq-Algerian Arabic.zip                      25-Apr-2020 05:47             3420182
Q74905-mis-Sursilvan.zip                           05-Nov-2019 03:37               14618
Q80-kan-Kannada.zip                                25-Apr-2020 05:47             3662223
Q83641-gcf-Guadeloupean Creole French.zip          05-Nov-2019 03:38             7412512
Q930-mis-Gascon dialect.zip                        05-Nov-2019 03:39           179656450
Q931-mis-Languedocien dialect.zip                  05-Nov-2019 03:40           191575650
lingualibre_full.zip                               17-May-2019 01:18          1989664440
```

**Comment by hugolpz** [comment]
This issue can soon be closed.

**Comment by mickeybarber** [comment]
I think some wikimedia servers limit download request because I have lot of return code "429" when I run create_dataset.
```
[1244/5392] Download
status_code: 429

status_code: 429

status_code: 429

status_code: 429
```

**Comment by hugolpz** [comment]
We don't have all zips indeed. Only 13 got through. We should have many more (70+ new or refreshed ?).

We will have to dig into that. But likely not this week since we got a conference to prepare.

**Comment by Poslovitch** [comment]
Looks like there's some rate limiting going on. I can't find its actual "duration" on Commons, but I'll definitely have to add some rate limitation in the download tool.

**Comment by mickeybarber** [comment]
Problems found:
- first script part: Download from commons.wikimedia.org only files from the last 5 days (works)
```
echo "--> Force the download of recent changes..."
/usr/bin/python3.8 ./CommonsDownloadTool/commons_download_tool.py --keep --sparqlurl https://lingualibre.org/bigdata/namespace/wdq/sparql --sparql "SELECT ?file ?filename WHERE { ${query} ${queryFilterRecent} }" --threads 4 --directory  ./tmp/datasets/raw/ --forcedownload --nozip --fileformat ogg
```
- second script part: 
```
echo "--> Download and package ALL sounds..."
/usr/bin/python3.8 ./CommonsDownloadTool/commons_download_tool.py --keep --sparqlurl https://lingualibre.org/bigdata/namespace/wdq/sparql --sparql "SELECT ?file ?filename WHERE { ${query} }" --threads 4 --directory  ./tmp/datasets/raw/ --output "/tmp/datasets/lingualibre_full.zip" --fileformat ogg
```
Try to download All LL files from commons.wikimedia.fr but, the request sparql fails (json not complet, java exception from the Blazegraph)
```
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.openrdf.query.QueryEvaluationException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: task=ChunkTask{query=9df8ee5e-00e1-4d73-94f7-6d0c47892f8d,bopId=22,partitionId=-1,sinkId=23,altSinkId=21}, cause=java.util.concurrent.ExecutionException: com.bigdata.rwstore.sector.MemoryManagerOutOfMemory
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:293)
	at com.bigdata.rdf.sail.webapp.QueryServlet.doSparqlQuery(QueryServlet.java:654)
	at com.bigdata.rdf.sail.webapp.QueryServlet.doPost(QueryServlet.java:273)
	at com.bigdata.rdf.sail.webapp.RESTServlet.doPost(RESTServlet.java:269)
	at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doPost(MultiTenancyServlet.java:193)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667)
	at org.wikidata.query.rdf.blazegraph.throttling.ThrottlingFilter.doFilter(ThrottlingFilter.java:317)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at ch.qos.logback.classic.helpers.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.wikidata.query.rdf.blazegraph.filters.ClientIPFilter.doFilter(ClientIPFilter.java:43)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: org.openrdf.query.QueryEvaluationException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: task=ChunkTask{query=9df8ee5e-00e1-4d73-94f7-6d0c47892f8d,bopId=22,partitionId=-1,sinkId=23,altSinkId=21}, cause=java.util.concurrent.ExecutionException: com.bigdata.rwstore.sector.MemoryManagerOutOfMemory
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlQueryTask.call(QueryServlet.java:865)
	at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlQueryTask.call(QueryServlet.java:671)
	at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: org.openrdf.query.QueryEvaluationException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: task=ChunkTask{query=9df8ee5e-00e1-4d73-94f7-6d0c47892f8d,bopId=22,partitionId=-1,sinkId=23,altSinkId=21}, cause=java.util.concurrent.ExecutionException: com.bigdata.rwstore.sector.MemoryManagerOutOfMemory
	at com.bigdata.rdf.sail.Bigdata2Sesame2BindingSetIterator.hasNext(Bigdata2Sesame2BindingSetIterator.java:188)
	at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
	at org.openrdf.query.QueryResults.report(QueryResults.java:155)
	at org.openrdf.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:76)
	at com.bigdata.rdf.sail.webapp.BigdataRDFContext$TupleQueryTask.doQuery(BigdataRDFContext.java:1713)
	at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask.innerCall(BigdataRDFContext.java:1569)
	at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask.call(BigdataRDFContext.java:1534)
	at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask.call(BigdataRDFContext.java:747)
	... 4 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.Exception: task=ChunkTask{query=9df8ee5e-00e1-4d73-94f7-6d0c47892f8d,bopId=22,partitionId=-1,sinkId=23,altSinkId=21}, cause=java.util.concurrent.ExecutionException: com.bigdata.rwstore.sector.MemoryManagerOutOfMemory
	at com.bigdata.rdf.sail.RunningQueryCloseableIterator.checkFuture(RunningQueryCloseableIterator.java:59)
	at com.bigdata.rdf.sail.RunningQueryCloseableIterator._hasNext(RunningQueryCloseableIterator.java:105)
	at com.bigdata.rdf.sail.RunningQueryCloseableIterator.hasNext(RunningQueryCloseableIterator.java:79)
	at com.bigdata.striterator.ChunkedWrappedIterator.hasNext(ChunkedWrappedIterator.java:197)
	at com.bigdata.rdf.sail.Bigdata2Sesame2BindingSetIterator.hasNext(Bigdata2Sesame2BindingSetIterator.java:134)
	... 11 more
Caused by: java.util.concurrent.ExecutionException: java.lang.Exception: task=ChunkTask{query=9df8ee5e-00e1-4d73-94f7-6d0c47892f8d,bopId=22,partitionId=-1,sinkId=23,altSinkId=21}, cause=java.util.concurrent.ExecutionException: com.bigdata.rwstore.sector.MemoryManagerOutOfMemory
	at com.bigdata.util.concurrent.Haltable.get(Haltable.java:273)
	at com.bigdata.bop.engine.AbstractRunningQuery.get(AbstractRunningQuery.java:1516)
	at com.bigdata.bop.engine.AbstractRunningQuery.get(AbstractRunningQuery.java:104)
	at com.bigdata.rdf.sail.RunningQueryCloseableIterator.checkFuture(RunningQueryCloseableIterator.java:46)
	... 15 more
Caused by: java.lang.Exception: task=ChunkTask{query=9df8ee5e-00e1-4d73-94f7-6d0c47892f8d,bopId=22,partitionId=-1,sinkId=23,altSinkId=21}, cause=java.util.concurrent.ExecutionException: com.bigdata.rwstore.sector.MemoryManagerOutOfMemory
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkTask.call(ChunkedRunningQuery.java:1367)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkTaskWrapper.run(ChunkedRunningQuery.java:926)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.bigdata.concurrent.FutureTaskMon.run(FutureTaskMon.java:63)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkFutureTask.run(ChunkedRunningQuery.java:821)
	... 3 more
Caused by: java.util.concurrent.ExecutionException: com.bigdata.rwstore.sector.MemoryManagerOutOfMemory
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkTask.call(ChunkedRunningQuery.java:1347)
	... 8 more
Caused by: com.bigdata.rwstore.sector.MemoryManagerOutOfMemory
	at com.bigdata.rwstore.sector.MemoryManager.getSectorFromFreeList(MemoryManager.java:646)
	at com.bigdata.rwstore.sector.MemoryManager.allocate(MemoryManager.java:675)
	at com.bigdata.rwstore.sector.AllocationContext.allocate(AllocationContext.java:195)
	at com.bigdata.rwstore.sector.AllocationContext.allocate(AllocationContext.java:169)
	at com.bigdata.rwstore.sector.AllocationContext.allocate(AllocationContext.java:159)
	at com.bigdata.rwstore.sector.AllocationContext.alloc(AllocationContext.java:359)
	at com.bigdata.rwstore.PSOutputStream.save(PSOutputStream.java:335)
	at com.bigdata.rwstore.PSOutputStream.getAddr(PSOutputStream.java:416)
	at com.bigdata.bop.solutions.SolutionSetStream.put(SolutionSetStream.java:297)
	at com.bigdata.bop.engine.LocalNativeChunkMessage.(LocalNativeChunkMessage.java:213)
	at com.bigdata.bop.engine.LocalNativeChunkMessage.(LocalNativeChunkMessage.java:147)
	at com.bigdata.bop.engine.StandaloneChunkHandler.handleChunk(StandaloneChunkHandler.java:92)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.outputChunk(ChunkedRunningQuery.java:1699)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.addReorderAllowed(ChunkedRunningQuery.java:1628)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.add(ChunkedRunningQuery.java:1569)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.add(ChunkedRunningQuery.java:1453)
	at com.bigdata.bop.bset.ConditionalRoutingOp$ConditionalRouteTask.call(ConditionalRoutingOp.java:215)
	at com.bigdata.bop.bset.ConditionalRoutingOp$ConditionalRouteTask.call(ConditionalRoutingOp.java:135)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkTask.call(ChunkedRunningQuery.java:1346)
	... 8 more
```
So Lingualibre_full.zip can't be created. Query result is too big. Server memory limit? Json limit?

- Last script part:
```
echo "--> Package each language individually"
for qidpath in  ./tmp/datasets/raw/*;
do
  qid=$(echo ${qidpath##*/} | cut -d'-' -f 1)
  if [[ $qid == Q* ]] ; then
    echo "--> Processing ${qid}..."
    /usr/bin/python3.8 ./CommonsDownloadTool/commons_download_tool.py --keep --sparqlurl https://lingualibre.org/bigdata/namespace/wdq/sparql --sparql "SELECT ?file ?filename WHERE { ${query} ?record prop:P4 entity:${qid}. }" --threads 4 --directory  /tmp/datasets/raw/ --output "/tmp/datasets/${qidpath##*/}.zip" --fileformat ogg
  fi
done
```
Download all files from each language found in the part 1, that is only languages recorded during last 5 days. That is why we have only 13 zip...

I think I can fix it if I split sparql query for each language.

**Comment by Poslovitch** [comment]
Good job for finding what the issue was.

> I think I can fix it if I split sparql query for each language.

@mickeybarber Go ahead. If that works, do not forget to commit on [lingua-libre/operations](https://github.com/lingua-libre/operations)

**Comment by Poslovitch** [comment]
Regarding the generation of the full dataset, this will need some deep internal rework. This was working fine for years since we weren't reaching memory limits. Now, the only way to avoid that is to split the request into smaller requests, and "sequentially" generate the full dataset out of it.

Avoid trying to generate the full dataset for now.

**Comment by hugolpz** [comment]
> Try to download All LL files from commons.wikimedia.fr 

Just to be sure..... the code actually says `.org` right ?

**Comment by mickeybarber** [comment]
> > Try to download All LL files from commons.wikimedia.fr
> 
> Just to be sure..... in the code actually says `.org` right ? Commons.wikimedia.fr does not exist. grimacing

Yes `.org`, not `.fr` ^^

**Comment by pamputt** [comment]
Oh I am just discovering this discussion. 
See also https://phabricator.wikimedia.org/T261519
I arrived at the same conclusion as you; optimise/split the query may solve the problem (at least for now).

**Comment by belett** [comment]
Hi,

There is two ways to split this query :
* split by language, adding a ``BIND ( entity:Q209 AS ?lang )`` (Q209 being Breton for the example, but I tried with Q21 French and it doesn't time out either)
* spit by slice, with ``LIMIT`` and ``OFFSET`` (see [https://www.w3.org/TR/rdf-sparql-query/#modOffset](W3C SPARQL specifications) ) and then remerge the results

I also need to take a closer look but maybe some other little things could be improved but the two point above is the more obvious and easy way to split the query.

**Comment by hugolpz** [comment]
Past month I wrote a downloader with nodejs and wikipaijs which has good performance.
Need futher test, then we can go.
Poslovitch is in this effort as well.

**Comment by Poslovitch** [comment]
As far as I know, the commons_download thingy is found on the server. I'll close this issue, since it's gotten out of scope for a long time. Please reopen dedicated and scoped issues, preferably on Phabricator. :smiley:
